import RecoilWrapper from "@/components/recoil-wrapper";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "자료구조",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <RecoilWrapper>{children}</RecoilWrapper>
      </body>
    </html>
  );
}
